HGShareBackstage/HGShare.Backstage/Controllers/AdminLogsController.cs
using System.ComponentModel;
using System.Linq;
using System.Web.Mvc;
using HGShare.Backstage.Controllers.Base;
using HGShare.Business;
using HGShare.Model;
using HGShare.Site.ActionResult;
using HGShare.Site.Config;
using HGShare.VWModel;
using Webdiyer.WebControls.Mvc;

namespace HGShare.Backstage.Controllers
{
    /// <summary>
    /// 访问日志管理
    /// </summary>
    [Description("访问日志管理")]
    public class AdminLogsController : BaseController
    {
        /// <summary>
        /// 列表
        /// </summary>
        /// <param name="page">页码</param>
        /// <returns></returns>
        [Description("访问日志列表")]
        public ActionResult Index(int? page)
        {
            int pageIndex = page.HasValue ? page.Value : 1;
            int pageSize = PageConfig.BackstagePageSize;
            int count, pageCount;
            var result = AdminLogs.AdminLogInfosToVModels(AdminLogs.GetAdminLogPageList(pageIndex, pageSize, null, null, out pageCount, out count));
            PagedList<AdminLogVModel> pl = result.ToPagedList(pageIndex, pageSize);
            pl.TotalItemCount = count;
            pl.CurrentPageIndex = pageIndex;
            return View(pl);
        }
        /// <summary>
        /// 删除AdminLog
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        [HttpPost]
        [Description("删除访问日志操作")]
        public JsonResult Delete(int id)
        {
            var result = new JsonResultModel { ResultState = AdminLogs.DeleteAdminLog(id) > 0 };
            return Json(result);
        }
        /// <summary>
        /// 删除AdminLog
        /// </summary>
        /// <param name="ids">ids</param>
        /// <returns></returns>
        [HttpPost]
        [Description("删除多个访问日志操作")]
        public JsonResult Deletes(int [] ids)
        {
            var result = new JsonResultModel { ResultState = AdminLogs.DeleteAdminLogs(ids) > 0 };
            return Json(result);
        }
    }
}

HGShareBackstage/HGShare.Backstage/Views/AdminLogs/Index.cshtml
@using HGShare.Site.Config
@using HGShare.VWModel
@using Webdiyer.WebControls.Mvc
@model PagedList<AdminLogVModel>
@{
    ViewBag.Title = "AdminLog列表";
    Layout = "~/Views/Shared/_HContentLayout.cshtml";
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>AdminLog列表</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form action="@Url.Action("Index", "AdminLogs")" method="GET">
                        <div class="row">
                            <div class="col-sm-5 m-b-xs">
                                <div class="btn-group hidden-xs" role="group">
                                    <button class="btn btn-default btn-outline" type="button" name="refresh" title="刷新" id="pagereload">
                                        <i class="fa fa-refresh"></i> 刷新
                                    </button>
                                    <button type="button" class="btn btn-outline btn-default" id="deletessubmit" title="删除选中项">
                                        <i class="fa fa-trash" aria-hidden="true"></i> 删除
                                    </button>
                                </div>
                            </div>
                            <div class="col-sm-4 m-b-xs">
                                <!--其它搜索条件-->
                            </div>
                            <div class="col-sm-3">
                                <div class="input-group">
                                    <input type="hidden" name="page" value="1" />
                                    <input type="text" placeholder="请输入关键词" class="input-sm form-control">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-sm btn-primary"> 搜索</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        <div class="checkbox checkbox-inline checkbox-primary">
                                            <input type="checkbox" value="0" id="selectitem" />
                                            <label for="selectitem"></label>
                                        </div>
                                    </th>
                                    <th>编号</th>
                                    <th>用户ID</th>
                                    <th>控制器</th>
                                    <th>控制器描述</th>
                                    <th>Action</th>
                                    <th>Action描述</th>
                                    <th>参数</th>
                                    <th>中主要ID</th>
                                    <th>IP</th>
                                    <th>Url</th>
                                    <th>记录时间</th>
                                    <th>请求方法</th>
                                    <th>Ajax访问</th>
                                    <th>UserAgent</th>
                                    
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (AdminLogVModel item in Model)
                                {
                                    <tr>
                                        <td>
                                            <div class="checkbox checkbox-inline checkbox-primary">
                                                <input type="checkbox" value="@item.Id" id="item_@item.Id" name="item" class="form-control" />
                                                <label for="item_@item.Id"></label>
                                            </div>
                                        </td>

                                        <td>@item.Id</td>
                                        <td>@item.UserId</td>
                                        <td>@item.Controllers</td>
                                        <td>@item.ControllersDsc</td>
                                        <td>@item.Action</td>
                                        <td>@item.ActionDsc</td>
                                        <td><a href="javascript:;" onclick="layer.alert('@item.Parameter')">查看</a></td>
                                        <td>@item.ActionId</td>
                                        <td>@item.Ip</td>
                                        <td>@item.Url</td>
                                        <td>@item.InTime</td>
                                        <td>@item.Method</td>
                                        <td>
                                            <span class="label label-@(item.IsAjax ? "success" : "default")">@(item.IsAjax ? "是" : "否")</span>
                                        </td>	
                                        <td><a href="javascript:;" onclick="layer.alert('@item.UserAgent')">查看</a></td>
                                        <td>
                                            <button class="btn btn-warning btn-sm delete_btn" type="button" data-id="@item.Id">
                                                <i class="fa fa-warning"></i> <span class="bold">删除</span>
                                            </button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="dataTables_info">共 @Model.TotalItemCount 项 @Model.TotalPageCount 页，当前第 @Model.CurrentPageIndex 页</div>
        </div>
        <div class="col-sm-6">
            <div class="dataTables_paginate paging_simple_numbers">
                <ul class="pagination">
                    @Html.Pager(Model, PageConfig.BackstageOptions)
                </ul>
            </div>
        </div>
    </div>
</div>
@section script_footer
{
    <script type="text/javascript">
        $(function () {
            /*通用删除操作*/
            ListTools.Delete.Init({ url: "@Url.Action("Delete","AdminLogs")", btn: ".delete_btn" });
            /*通用多选删除操作*/
            ListTools.Deletes.Init({ url: "@Url.Action("Deletes","AdminLogs")", btn: "#deletessubmit", itemname: "item" });
            /*选择操作*/
            ListTools.SelectBox.Init({ btn: "#selectitem", itemname: "item" });
            /*刷新操作*/
            ListTools.PageReload.Init({ btn: "#pagereload" });
        })
    </script>
}