HGShareBackstage/HGShare.Backstage/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web.Mvc;
using HGShare.Backstage.Controllers.Base;
using HGShare.Business;
using HGShare.Model;
using HGShare.Site;
using HGShare.Site.ActionResult;
using HGShare.Site.Config;
using HGShare.VWModel;
using Newtonsoft.Json;
using Webdiyer.WebControls.Mvc;

namespace HGShare.Backstage.Controllers
{   
    /// <summary>
    /// 角色管理
    /// </summary>
    [Description("角色管理")]
    public class RolesController : BaseController
    {
        /// <summary>
        /// 列表
        /// </summary>
        /// <param name="page">页码</param>
        /// <returns></returns>
        [Description("角色列表")]
        public ActionResult Index(int? page)
        {
            int pageIndex = page.HasValue ? page.Value : 1;
            int pageSize = PageConfig.BackstagePageSize;
            int count, pageCount;
            var result = Roles.RoleInfosToVModels(Roles.GetRolePageList(pageIndex, pageSize, null, null, out pageCount, out count));
            PagedList<RoleVModel> pl = result.ToPagedList(pageIndex, pageSize);
            pl.TotalItemCount = count;
            pl.CurrentPageIndex = pageIndex;
            return View(pl);
        }
        /// <summary>
        /// 删除角色
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [Description("删除角色操作")]
        public JsonResult Delete(int id)
        {
            var result = new JsonResultModel { ResultState = Roles.DeleteRole(id) > 0 };
            return Json(result);
        }
        /// <summary>
        /// 删除Role
        /// </summary>
        /// <param name="ids">ids</param>
        /// <returns></returns>
        [HttpPost]
        [Description("删除多个Role操作")]
        public JsonResult Deletes(int[] ids)
        {
            var result = new JsonResultModel { ResultState = Roles.DeleteRoles(ids) > 0 };
            return Json(result);
        }
        /// <summary>
        /// 添加角色
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Description("添加角色页面")]
        public ActionResult Add()
        {
            var vm = new RoleVModel(){IsSuper = false};
            return View(vm);
        }
        /// <summary>
        /// 添加角色
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Description("添加角色操作")]
        public JsonResult Add(RoleVModel model)
        {
            var result = new JsonResultModel();
            if (ModelState.IsValid)
            {
                //add 
                result.ResultState = Roles.AddRole(Roles.RoleVModelToInfo(model))>0;
            }
            else
            {
                result.ResultState = false;
                result.Message = ModelStateHelper.GetAllErrorMessage(ModelState);
            }

            return Json(result);
        }
        /// <summary>
        /// 修改Role
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Description("修改角色页面")]
        public ActionResult Edit(int id)
        {
            var model = Roles.RoleInfoToVModel(Roles.GetRoleInfo(id));
            return View(model);
        }
        /// <summary>
        /// 修改Role
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Description("修改角色操作")]
        public JsonResult Edit(RoleVModel model)
        {
            var result = new JsonResultModel();
            if (ModelState.IsValid)
            {
                //edit user
                result.ResultState = Roles.UpdateRole(Roles.RoleVModelToInfo(model)) > 0;
            }
            else
            {
                result.ResultState = false;
                result.Message = ModelStateHelper.GetAllErrorMessage(ModelState);
            }

            return Json(result);
        }

        /// <summary>
        /// 分配资源
        /// </summary>
        /// <param name="id">角色id</param>
        /// <returns></returns>
        [HttpGet]
        [Description("分配模块页面")]
        public ActionResult AllocationModul(int id)
        {
            //查询已有模块 在前端进行默认选中
            int[] mIds = RoleModuls.GetMIds(id);
            ViewBag.SelectedIds = JsonConvert.SerializeObject(mIds.Select(n => "tree_node_" + n).ToList());
            //查询资源树
            var moduls = Moduls.ModulInfosToTreeVModels(Moduls.GetAllModul(id));
            ViewBag.RId = id;
            return View(moduls);
        }
        /// <summary>
        /// 分配资源
        /// </summary>
        /// <param name="rid"></param>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        [Description("分配模块操作")]
        public ActionResult AllocationModul(int rid,string ids)
        {
            var result = new JsonResultModel()
            {
                ResultState = true
            };
            
            //根据角色id删除原有关系
            RoleModuls.DeleteRoleModuls(rid);
            //根据选中的模块新建关系
            List<RoleModulInfo> rolemoduls = ids.Split(',').Where(n=>!string.IsNullOrEmpty(n)).Select(n => new RoleModulInfo
            {
                RId = rid,
                MId = int.Parse(n)

            }).ToList();

            RoleModuls.AddRoleModuls(rolemoduls);
            return Json(result);
        }
    }
}

HGShareBackstage/HGShare.Backstage/Views/Roles/Add.cshtml
@using HGShare.Site
@model HGShare.VWModel.RoleVModel
@{
    ViewBag.Title = "添加角色";
    Layout = "~/Views/Shared/_HContentLayout.cshtml";
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加角色</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Add", "Roles", FormMethod.Post, new { @class = "form-horizontal", id = "addform" }))
                    {
                        <div class="form-group">
                            <label class="col-sm-3 control-label">角色名</label>
                            <div class="col-sm-5">
                               @Html.TextBoxFor(n => n.RName, new { @class = "form-control", @placeholder = "请输入角色名" })
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.RName)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">是否是超级角色</label>
                            <div class="col-sm-5">
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.IsSuper, true, new { id = "IsSuper1" })
                                    <label for="IsSuper1">
                                        是
                                    </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.IsSuper, false, new { id = "IsSuper2" })
                                    <label for="IsSuper2">
                                        否
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.IsSuper)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">描述</label>
                            <div class="col-sm-5">
                                @Html.TextAreaFor(n => n.Description, new { @class = "form-control", @placeholder = "请输入描述" })
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.Description)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">发帖是否需要审核</label>
                            <div class="col-sm-5">
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.ArticleNeedVerified, true, new { id = "ArticleNeedVerified1" })
                                    <label for="ArticleNeedVerified1">
                                        是
                                    </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.ArticleNeedVerified, false, new { id = "ArticleNeedVerified2" })
                                    <label for="ArticleNeedVerified2">
                                        否
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.ArticleNeedVerified)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">评论是否需要审核</label>
                            <div class="col-sm-5">
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.CommentNeedVerified, true, new { id = "CommentNeedVerified1" })
                                    <label for="CommentNeedVerified1">
                                        是
                                    </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.CommentNeedVerified, false, new { id = "CommentNeedVerified2" })
                                    <label for="CommentNeedVerified2">
                                        否
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.CommentNeedVerified)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-12 col-sm-offset-3">
                                @Html.HiddenFor(n => n.Id)
                                <button class="btn btn-primary" type="submit" id="submit">保存内容</button>
                                <button class="btn btn-white" type="button" onclick="window.history.back(-1);">取消</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section script_footer
{
    <!--表单验证-->
    <script src="@Url.StaticFile("~/hplus/js/plugins/validate/jquery.validate.js?v=1.35")"></script>
    <script src="@Url.StaticFile("~/hplus/js/plugins/validate/jquery.validate.unobtrusive.js?v=1.40")"></script>
    <script src="@Url.StaticFile("~/hplus/js/jquery.form.js")"></script>
    <script type="text/javascript">
        ValidataTools.Init({
            backurl: "@Url.Action("Index", "Roles")",
            form: $("#addform"),
            submitbtn: $("#submit"),
            btntext: "保存内容",
            tipstype:"添加"
        });
    </script>
}

HGShareBackstage/HGShare.Backstage/Views/Roles/AllocationModul.cshtml
@model List<HGShare.VWModel.TreeVModel>
@using HGShare.Site
@using Newtonsoft.Json
@{
    ViewBag.Title = "分配模块";
    Layout = "~/Views/Shared/_HContentLayout.cshtml";
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>分配模块</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <form>
                            <div class="form-group">
                                <div id="using_json">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <button class="btn btn-primary btn-sm" type="button" id="submitbtn">确定分配</button>
                                <button class="btn btn-white" type="button" onclick="window.history.back(-1);">取消</button>
                            </div>
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
@section script_header
{
<!--树-->
<link href="@Url.StaticFile("~/hplus/css/plugins/jsTree/style.min.css")" rel="stylesheet" />
}
@section script_footer
{
    <!--树-->
    <script type="text/javascript" src="@Url.StaticFile("~/hplus/js/plugins/jsTree/jstree.min.js")"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var tree = $("#using_json").jstree({
                "core": {
                    "multiple": true,
                    "data": @Html.Raw(JsonConvert.SerializeObject(Model))
                },
                "checkbox": {
                    "keep_selected_style": false //是否显示节点的选中样
                },
                "plugins": ["checkbox"]
            }).on('click.jstree', function(event) {
                //点击事件
            }).on('changed.jstree', function(e, data) {
                //选中事件
            }).on('ready.jstree', function() {
                /*默认选中已选模块*/
                tree.jstree().select_node(@Html.Raw(ViewBag.SelectedIds));
                tree.jstree().open_node(@Html.Raw(ViewBag.SelectedIds));
                open_node
            });
            /*提交选中的模块*/
            $("#submitbtn").on("click", function() {
                var selectednodeids = tree.jstree().get_checked();
                var ids = [];
                for (var i = 0; i < selectednodeids.length; i++) {
                    ids.push(selectednodeids[i].replace("tree_node_",''));
                }
                //更新数据
                hgajax.post("@Url.Action("AllocationModul", "Roles")", {rid:@ViewBag.RId,ids:ids.join(',')}, function(result) {
                    window.location.reload();
                });
            });
        });

    </script>
}

HGShareBackstage/HGShare.Backstage/Views/Roles/Edit.cshtml
@using HGShare.Site
@model HGShare.VWModel.RoleVModel
@{
    ViewBag.Title = "修改角色";
    Layout = "~/Views/Shared/_HContentLayout.cshtml";
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>修改角色</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Edit", "Roles", FormMethod.Post, new { @class = "form-horizontal", id = "addform" }))
                    {
                        <div class="form-group">
                            <label class="col-sm-3 control-label">角色名</label>
                            <div class="col-sm-5">
                                @Html.TextBoxFor(n => n.RName, new { @class = "form-control", @placeholder = "请输入角色名" })
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.RName)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">是否是超级角色</label>
                            <div class="col-sm-5">
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.IsSuper, true, new { id = "IsSuper1" })
                                    <label for="IsSuper1">
                                        是
                                    </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.IsSuper, false, new { id = "IsSuper2" })
                                    <label for="IsSuper2">
                                        否
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.IsSuper)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">是否禁用</label>
                            <div class="col-sm-5">
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.IsDel, true, new { id = "IsDel1" })
                                    <label for="IsDel1">
                                        是
                                    </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.IsDel, false, new { id = "IsDel2" })
                                    <label for="IsDel2">
                                        否
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.IsSuper)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">描述</label>
                            <div class="col-sm-5">
                                @Html.TextAreaFor(n => n.Description, new { @class = "form-control", @placeholder = "请输入描述" })
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.Description)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">发帖是否需要审核</label>
                            <div class="col-sm-5">
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.ArticleNeedVerified, true, new { id = "ArticleNeedVerified1" })
                                    <label for="ArticleNeedVerified1">
                                        是
                                    </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.ArticleNeedVerified, false, new { id = "ArticleNeedVerified2" })
                                    <label for="ArticleNeedVerified2">
                                        否
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.ArticleNeedVerified)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">评论是否需要审核</label>
                            <div class="col-sm-5">
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.CommentNeedVerified, true, new { id = "CommentNeedVerified1" })
                                    <label for="CommentNeedVerified1">
                                        是
                                    </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    @Html.RadioButtonFor(n => n.CommentNeedVerified, false, new { id = "CommentNeedVerified2" })
                                    <label for="CommentNeedVerified2">
                                        否
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                @Html.ValidationMessageFor(n => n.CommentNeedVerified)
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-12 col-sm-offset-3">
                                @Html.HiddenFor(n => n.Id)
                                <button class="btn btn-primary" type="submit" id="submit">保存内容</button>
                                <button class="btn btn-white" type="button" onclick="window.history.back(-1);">取消</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section script_footer
{
    <!--表单验证-->
    <script src="@Url.StaticFile("~/hplus/js/plugins/validate/jquery.validate.js?v=1.35")"></script>
    <script src="@Url.StaticFile("~/hplus/js/plugins/validate/jquery.validate.unobtrusive.js?v=1.40")"></script>
    <script src="@Url.StaticFile("~/hplus/js/jquery.form.js")"></script>
    <script type="text/javascript">
        ValidataTools.Init({
            backurl: "@Url.Action("Index", "Roles")",
            form: $("#addform"),
            submitbtn: $("#submit"),
            btntext: "保存内容",
            tipstype:"修改"
        });
    </script>
}

HGShareBackstage/HGShare.Backstage/Views/Roles/Index.cshtml
@using HGShare.Site.Config
@using HGShare.VWModel
@using Webdiyer.WebControls.Mvc
@model PagedList<RoleVModel>
@{
    ViewBag.Title = "Role列表";
    Layout = "~/Views/Shared/_HContentLayout.cshtml";
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>角色列表</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form action="@Url.Action("Index", "Roles")" method="GET">
                        <div class="row">
                            <div class="col-sm-5 m-b-xs">
                                <div class="btn-group hidden-xs" role="group">
                                    <a href="@Url.Action("Add","Roles")" class="btn btn-outline btn-default">
                                        <i class="fa fa-pencil-square" aria-hidden="true"></i> 添加
                                    </a> 
                                    <button class="btn btn-default btn-outline" type="button" name="refresh" title="刷新" id="pagereload">
                                        <i class="fa fa-refresh"></i> 刷新
                                    </button> 
                                    <button type="button" class="btn btn-outline btn-default" id="deletessubmit">
                                        <i class="fa fa-trash" aria-hidden="true"></i> 删除
                                    </button> 
                                </div>
                                </div>
                            <div class="col-sm-4 m-b-xs">
                                <!--其它搜索条件-->
                            </div>
                            <div class="col-sm-3">
                                <div class="input-group">
                                    <input type="hidden" name="page" value="1" />
                                    <input type="text" placeholder="请输入关键词" class="input-sm form-control">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-sm btn-primary"> 搜索</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        <div class="checkbox checkbox-inline checkbox-primary">
                                            <input type="checkbox" value="0" id="selectdeleteitem" />
                                            <label for="selectdeleteitem"></label>
                                        </div>
                                    </th>
                                    <th>角色名</th>
                                    <th>添加时间</th>
                                    <th>是否禁用</th>
                                    <th>是否是超级角色</th>
                                    <th>发帖是否需要审核</th>
                                    <th>评论是否需要审核</th>
                                    <th>描述</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (RoleVModel item in Model)
                                {
                                    <tr>
                                        <td>
                                            <div class="checkbox checkbox-inline checkbox-primary">
                                                <input type="checkbox" value="@item.Id" id="deleteitem_@item.Id" name="deleteitem" />
                                                <label for="deleteitem_@item.Id"></label>
                                            </div>
                                        </td>

                                        <td>@item.RName</td>
                                        <td>@item.CreateTime</td>
                                        <td>
                                            <span class="label label-@(item.IsDel ? "success" : "default")">@(item.IsDel ? "是" : "否")</span>
                                        </td>
                                        <td>
                                            <span class="label label-@(item.IsSuper ? "success" : "default")">@(item.IsSuper ? "是" : "否")</span>
                                        </td>
                                        <td>
                                            <span class="label label-@(item.ArticleNeedVerified ? "success" : "default")">@(item.ArticleNeedVerified ? "是" : "否")</span>
                                        </td>
                                        <td>
                                            <span class="label label-@(item.CommentNeedVerified ? "success" : "default")">@(item.CommentNeedVerified ? "是" : "否")</span>
                                        </td>	
                                        <td>@item.Description</td>	
                                        <td>
                                            <a class="btn btn-info btn-sm" href="@Url.Action("Edit","Roles")?Id=@item.Id"><i class="fa fa-paste"></i> 编辑</a>
                                            <button class="btn btn-warning btn-sm delete_btn" type="button" data-id="@item.Id">
                                                <i class="fa fa-warning"></i> <span class="bold">删除</span>
                                            </button>
                                            <a class="btn btn-success btn-sm" href="@Url.Action("AllocationModul", "Roles")?Id=@item.Id">
                                                <span class="bold">分配资源</span>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="dataTables_info">共 @Model.TotalItemCount 项 @Model.TotalPageCount 页，当前第 @Model.CurrentPageIndex 页</div>
        </div>
        <div class="col-sm-6">
            <div class="dataTables_paginate paging_simple_numbers">
                <ul class="pagination">
                    @Html.Pager(Model, PageConfig.BackstageOptions)
                </ul>
            </div>
        </div>
    </div>
</div>
@section script_footer
{
    <script type="text/javascript">
        $(function () {
            /*通用删除操作*/
            ListTools.Delete.Init({ url: "@Url.Action("Delete","Roles")", btn: ".delete_btn" });
            /*通用多选删除操作*/
            ListTools.Deletes.Init({ url: "@Url.Action("Deletes","Roles")", btn: "#deletessubmit", itemname: "deleteitem" });
            /*删除选择操作*/
            ListTools.DeleteSelectBox.Init({ btn: "#selectdeleteitem", itemname: "deleteitem" });
            /*刷新操作*/
            ListTools.PageReload.Init({ btn: "#pagereload" });
        })
    </script>
}